# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08999fc5935441341c218db745f872832b753f6ddc7a97ca4e14584fb0476f8213cb83f3642ca237e1f01ec07e6a3a209fccd9bb5e0a181bd2ac495f42d778e2
  aliyun_oss_id: GJiXFxmj0tpMa112
  aliyun_oss_secret: a4n9Ghx6chOwWpSrNZpZ5XG6CDbQ4N

test:
  secret_key_base: 0a8e8801a0cf7141c1f59d06031c2eb3d99ebe6379b2318779d1fa1617da4052114545c2afde459bc802cef2595ab6b5603bace9ca77646c009d52d43af7d6d5
  aliyun_oss_id: GJiXFxmj0tpMa112
  aliyun_oss_secret: a4n9Ghx6chOwWpSrNZpZ5XG6CDbQ4N

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aliyun_oss_id: GJiXFxmj0tpMa112
  aliyun_oss_secret: a4n9Ghx6chOwWpSrNZpZ5XG6CDbQ4N
